name:                servn
version:             0.1.0.0
homepage:            https://github.com/githubuser/servn#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - servant
  - servant-options
  - warp
  - text
  - safe
  - aeson
  - servant-server
  - time

executables:
  servn:
    source-dirs:      src
    main:             Main.hs
